@startuml
sprite $gatsby [64x64/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFF
FFFFFFFFFFFFBBBBBBBBBBBBBBBAA976679AABBBBBBBBBBBBBBBFFFFFFFFFFFF
FFFFFFFFFFFBBBBBBBBBBBBBA500000000000049ABBBBBBBBBBBBFFFFFFFFFFF
FFFFFFFFFFBBBBBBBBBBBB70000000000000000006BBBBBBBBBBBBFFFFFFFFFF
FFFFFFFFFBBBBBBBBBBB700000000000000000000005BBBBBBBBBBBFFFFFFFFF
FFFFFFFFBBBBBBBBBBA100000000000000000000000019BBBBBBBBBBFFFFFFFF
FFFFFFFFBBBBBBBBB60000000038AAABBAAA83000000005BBBBBBBBBFFFFFFFF
FFFFFFFBBBBBBBBB400000018ABBBBBBBBBBBBA810000003BBBBBBBBBFFFFFFF
FFFFFFBBBBBBBBB40000007ABBBBBBBBBBBBBBBBA80000002BBBBBBBBBFFFFFF
FFFFFFBBBBBBBB4000003ABBBBBBBBBBBBBBBBBBBBA4000003BBBBBBBBFFFFFF
FFFFFBBBBBBBB7000005ABBBBBBBBBBBBBBBBBBBBBBB6000005BBBBBBBBFFFFF
FFFFFBBBBBBBA000006BBBBBBBBBBBBBBBBBBBBBBBBBB700005BBBBBBBBFFFFF
FFFFBBBBBBBB100005BBBBBBBBBBBBBBBBBBBBBBBBBBBB7006BBBBBBBBBBFFFF
FFFFBBBBBBB700003ABBBBBBBBBBBBBBBBBBBBBBBBBBBBB57BBBBBBBBBBBFFFF
FFFBBBBBBBB00000ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFF
FFFBBBBBBB800007BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFF
FFFBBBBBBB00001ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFF
FFBBBBBBBA00008BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBBB60000ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBBB100002ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBBB9000002ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBBBB9000002ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBBBBB9000002ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBBBBBB9000002ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBBBBBBB9000002BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFF
FFBBBBBB9BBBBB9000002BBBBBBBBBBBBBBBBBBB5000000000000006BBBBBBFF
FFBBBBBB73BBBBB9000002BBBBBBBBBBBBBBBBBB5000000000000007BBBBBBFF
FFBBBBBB803BBBBB8000002BBBBBBBBBBBBBBBBB5000000000000009BBBBBBFF
FFBBBBBBA003BBBBB8000002BBBBBBBBBBBBBBBB500000000000000ABBBBBBFF
FFBBBBBBA0003BBBBB8000002BBBBBBBBBBBBBBBA99999999970000ABBBBBBFF
FFBBBBBBA00003ABBBB8000002BBBBBBBBBBBBBBBBBBBBBBBB40000BBBBBBBFF
FFBBBBBBB300003ABBBB8000002BBBBBBBBBBBBBBBBBBBBBBA00005BBBBBBBFF
FFBBBBBBB9000003ABBBB8000002BBBBBBBBBBBBBBBBBBBBB80000ABBBBBBBFF
FFFBBBBBBA0000003ABBBB8000002BBBBBBBBBBBBBBBBBBBB20000BBBBBBBFFF
FFFBBBBBBB50000003ABBBB8000002BBBBBBBBBBBBBBBBBB800007BBBBBBBFFF
FFFBBBBBBBA00000003ABBBB8000002BBBBBBBBBBBBBBBBA10000BBBBBBBBFFF
FFFFBBBBBBB400000003ABBBB8000002BBBBBBBBBBBBBBB400007BBBBBBBFFFF
FFFFBBBBBBBB000000003ABBBB8000002ABBBBBBBBBBBB600001BBBBBBBBFFFF
FFFFFBBBBBBB8000000003ABBBB8000002ABBBBBBBBBB700000ABBBBBBBFFFFF
FFFFFBBBBBBBB4000000003ABBBB8000002ABBBBBBBB6000006BBBBBBBBFFFFF
FFFFFFBBBBBBBB2000000003ABBBB8000002ABBBBBA4000004BBBBBBBBFFFFFF
FFFFFFBBBBBBBBB2000000002ABBBB9000002ABBB81000004BBBBBBBBBFFFFFF
FFFFFFFBBBBBBBBB2000000002ABBBB9000002A820000004BBBBBBBBBFFFFFFF
FFFFFFFFBBBBBBBBB4000000002ABBBB900000000000007BBBBBBBBBFFFFFFFF
FFFFFFFFBBBBBBBBBB8000000002ABBBB900000000001ABBBBBBBBBBFFFFFFFF
FFFFFFFFFBBBBBBBBBBB500000001BBBBB9000000007BBBBBBBBBBBFFFFFFFFF
FFFFFFFFFFBBBBBBBBBBBB60000001BBBBB9000008BBBBBBBBBBBBFFFFFFFFFF
FFFFFFFFFFFBBBBBBBBBBBBBA500001BBBBB916ABBBBBBBBBBBBBFFFFFFFFFFF
FFFFFFFFFFFFBBBBBBBBBBBBBBBAA988BBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFF
FFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}


!define TOOL_GATSBY(_alias) ENTITY(rectangle,black,gatsby,_alias,TOOL GATSBY)
!define TOOL_GATSBY(_alias, _label) ENTITY(rectangle,black,gatsby,_label, _alias,TOOL GATSBY)
!define TOOL_GATSBY(_alias, _label, _shape) ENTITY(_shape,black,gatsby,_label, _alias,TOOL GATSBY)
!define TOOL_GATSBY(_alias, _label, _shape, _color) ENTITY(_shape,_color,gatsby,_label, _alias,TOOL GATSBY)
skinparam folderBackgroundColor<<TOOL GATSBY>> White
@enduml

